# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.sirwashington
archives_base_name=vs_turbojets

# Dependencies
fabric_kotlin_version=1.13.5+kotlin.2.2.10
fabric_version=0.92.6+1.20.1
vs2_version=2.5.0-beta.3+237c68468b
vs_core_version=1.1.0+6abae09042
fabric_api_version=0.90.7+1.20.1
homepage=https://valkyrienskies.org/
sources=https://github.com/ValkyrienSkies/Eureka
issue_tracker=https://github.com/ValkyrienSkies/Eureka/issues